#!/usr/bin/env bash

set -euo pipefail

project_name="thermasnap-smoke-${GITHUB_RUN_ID:-$$}"
production_project_name="${project_name}-production"
app_port="${THERMASNAP_SMOKE_APP_PORT:-18080}"
vite_port="${THERMASNAP_SMOKE_VITE_PORT:-15173}"
postgres_port="${THERMASNAP_SMOKE_POSTGRES_PORT:-15432}"
production_nginx_port="${THERMASNAP_PRODUCTION_SMOKE_NGINX_PORT:-18081}"
production_postgres_port="${THERMASNAP_PRODUCTION_SMOKE_POSTGRES_PORT:-15433}"
media_probe="storage/app/public/docker-smoke.txt"
queue_probe="storage/app/public/docker-queue-smoke.txt"
public_asset_probe="storage/app/public/templates/docker-public-smoke.txt"
private_capture_probe="storage/app/public/captures/docker-private-smoke.jpg"
private_receipt_probe="storage/app/public/receipts/docker-private-smoke.png"
temporary_root="$(mktemp -d)"
production_app_env="$temporary_root/app.env"
production_postgres_env="$temporary_root/postgres.env"
production_compose_env="$temporary_root/compose.env"
production_media="$temporary_root/media"
production_backups="$temporary_root/backups"
production_backup_env="$temporary_root/backup.env"
production_pgpass="$temporary_root/.pgpass"
restored_media="$temporary_root/restored-media"
env_backup=""

if [[ -f .env.docker ]]; then
    env_backup="$(mktemp)"
    cp .env.docker "$env_backup"
fi

# Run Docker Compose against the isolated production environment generated by
# this smoke test so no host production configuration is ever read.
prod_compose() {
    docker compose \
        --env-file "$production_compose_env" \
        -p "$production_project_name" \
        -f compose.production.yaml \
        "$@"
}

# Restore the developer environment and remove every isolated container,
# network, volume, test secret, and media artifact created by this script.
cleanup() {
    docker compose \
        -p "$project_name" \
        down \
        --volumes \
        --remove-orphans >/dev/null 2>&1 || true

    if [[ -f "$production_compose_env" ]]; then
        prod_compose down --volumes --remove-orphans >/dev/null 2>&1 || true
    fi

    rm -f \
        "$media_probe" \
        "$queue_probe" \
        "$public_asset_probe" \
        "$private_capture_probe" \
        "$private_receipt_probe"

    if [[ -n "$env_backup" && -f "$env_backup" ]]; then
        cp "$env_backup" .env.docker
        rm -f "$env_backup"
    else
        rm -f .env.docker
    fi

    if [[ -d "$temporary_root" ]]; then
        docker run \
            --rm \
            --entrypoint chown \
            -v "$temporary_root:/thermasnap-smoke" \
            postgres:18.6-bookworm \
            -R "$(id -u):$(id -g)" \
            /thermasnap-smoke >/dev/null 2>&1 || true

        rm -rf "$temporary_root"
    fi
}

# Poll an HTTP endpoint until it succeeds or the bounded retry count is
# exhausted.
wait_for_http() {
    local url="$1"
    local attempts="${2:-30}"

    for ((attempt = 1; attempt <= attempts; attempt++)); do
        if curl --fail --silent --show-error "$url" >/dev/null 2>&1; then
            return 0
        fi

        sleep 2
    done

    echo "HTTP endpoint did not become ready: $url" >&2
    return 1
}

# Wait for a container health check to report healthy and fail immediately if
# the container exits or becomes explicitly unhealthy.
wait_for_container_health() {
    local container_id="$1"
    local service_name="$2"
    local attempts="${3:-30}"

    for ((attempt = 1; attempt <= attempts; attempt++)); do
        local state
        local health

        state="$(docker inspect --format '{{.State.Status}}' "$container_id")"
        health="$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$container_id")"

        if [[ "$health" == "healthy" ]]; then
            return 0
        fi

        if [[ "$state" == "exited" || "$state" == "dead" || "$health" == "unhealthy" ]]; then
            echo "Container failed health verification: $service_name ($state/$health)" >&2
            docker logs "$container_id" >&2 || true
            return 1
        fi

        sleep 2
    done

    echo "Container did not become healthy: $service_name" >&2
    docker logs "$container_id" >&2 || true
    return 1
}

# Assert that production Compose applied non-zero CPU/memory bounds and the
# configured bounded json-file logging policy to a running service.
assert_production_runtime_bounds() {
    local service_name="$1"
    local container_id
    local memory
    local nano_cpus
    local log_driver
    local log_max_size
    local log_max_files

    container_id="$(prod_compose ps -q "$service_name")"
    memory="$(docker inspect --format '{{.HostConfig.Memory}}' "$container_id")"
    nano_cpus="$(docker inspect --format '{{.HostConfig.NanoCpus}}' "$container_id")"
    log_driver="$(docker inspect --format '{{.HostConfig.LogConfig.Type}}' "$container_id")"
    log_max_size="$(docker inspect --format '{{index .HostConfig.LogConfig.Config "max-size"}}' "$container_id")"
    log_max_files="$(docker inspect --format '{{index .HostConfig.LogConfig.Config "max-file"}}' "$container_id")"

    (( memory > 0 ))
    (( nano_cpus > 0 ))
    [[ "$log_driver" == "json-file" ]]
    [[ "$log_max_size" == "10m" ]]
    [[ "$log_max_files" == "5" ]]
}

trap cleanup EXIT

cp .env.docker.example .env.docker

app_key="base64:$(openssl rand -base64 32 | tr -d '\n')"
sed -i "s|^APP_KEY=.*$|APP_KEY=${app_key}|" .env.docker

export APP_UID
export APP_GID
export APP_PORT="$app_port"
export VITE_PORT="$vite_port"
export POSTGRES_HOST_PORT="$postgres_port"

APP_UID="$(id -u)"
APP_GID="$(id -g)"

docker compose -p "$project_name" config --quiet
docker compose -p "$project_name" build app
docker compose -p "$project_name" up -d postgres

docker compose \
    -p "$project_name" \
    run --rm --no-deps app \
    php artisan migrate --force

docker compose \
    -p "$project_name" \
    up -d app worker scheduler vite nginx

wait_for_http "http://127.0.0.1:${app_port}/up"
wait_for_http "http://127.0.0.1:${vite_port}/@vite/client"

curl \
    --fail \
    --silent \
    --show-error \
    --dump-header /tmp/thermasnap-redirect-headers.txt \
    --output /dev/null \
    "http://127.0.0.1:${app_port}/admin"

grep -q "^Location: http://127.0.0.1:${app_port}/login" /tmp/thermasnap-redirect-headers.txt
rm -f /tmp/thermasnap-redirect-headers.txt

docker compose -p "$project_name" exec -T app php artisan config:show database.default | grep -q pgsql
docker compose -p "$project_name" exec -T app php artisan config:show filesystems.default | grep -q public
docker compose -p "$project_name" exec -T app php artisan config:show queue.default | grep -q database
docker compose -p "$project_name" exec -T app php artisan migrate:status >/dev/null

schedule_output="$(docker compose -p "$project_name" exec -T app php artisan schedule:list)"
grep -q 'photobooth:expire-sessions' <<<"$schedule_output"
grep -q 'media:prune-expired' <<<"$schedule_output"

docker compose \
    -p "$project_name" \
    exec -T worker \
    sh -c 'tr "\0" " " </proc/1/cmdline' | grep -q 'queue:work'

docker compose \
    -p "$project_name" \
    exec -T scheduler \
    sh -c 'tr "\0" " " </proc/1/cmdline' | grep -q 'schedule:work'

docker compose \
    -p "$project_name" \
    exec -T app \
    php artisan tinker --execute='dispatch(function (): void { file_put_contents(storage_path("app/public/docker-queue-smoke.txt"), "queue-ok"); });'

for _ in {1..30}; do
    if [[ -f "$queue_probe" ]]; then
        break
    fi

    sleep 1
done

test -f "$queue_probe"
grep -q 'queue-ok' "$queue_probe"

docker compose -p "$project_name" exec -T scheduler php artisan schedule:run --verbose
docker compose -p "$project_name" exec -T app php artisan media:prune-expired

mkdir -p \
    "$(dirname "$public_asset_probe")" \
    "$(dirname "$private_capture_probe")" \
    "$(dirname "$private_receipt_probe")"

printf 'persistent-media-ok\n' > "$media_probe"
printf 'public-template-ok\n' > "$public_asset_probe"
printf 'private-capture\n' > "$private_capture_probe"
printf 'private-receipt\n' > "$private_receipt_probe"

curl --fail --silent "http://127.0.0.1:${app_port}/storage/docker-smoke.txt" | grep -q 'persistent-media-ok'
curl --fail --silent "http://127.0.0.1:${app_port}/storage/templates/docker-public-smoke.txt" | grep -q 'public-template-ok'

[[ "$(curl --silent --output /dev/null --write-out '%{http_code}' "http://127.0.0.1:${app_port}/storage/captures/docker-private-smoke.jpg")" == "404" ]]
[[ "$(curl --silent --output /dev/null --write-out '%{http_code}' "http://127.0.0.1:${app_port}/storage/receipts/docker-private-smoke.png")" == "404" ]]

docker compose \
    -p "$project_name" \
    restart app worker scheduler nginx postgres

wait_for_http "http://127.0.0.1:${app_port}/up"

curl --fail --silent "http://127.0.0.1:${app_port}/storage/docker-smoke.txt" | grep -q 'persistent-media-ok'
docker compose -p "$project_name" exec -T app php artisan migrate:status >/dev/null

docker compose -p "$project_name" down --volumes --remove-orphans

rm -f \
    "$media_probe" \
    "$queue_probe" \
    "$public_asset_probe" \
    "$private_capture_probe" \
    "$private_receipt_probe"

mkdir -p "$production_media" "$production_backups" "$restored_media"

production_app_key="base64:$(openssl rand -base64 32 | tr -d '\n')"
production_postgres_password="$(openssl rand -hex 24)"
production_app_password="$(openssl rand -hex 24)"
production_backup_password="$(openssl rand -hex 24)"

cat > "$production_app_env" <<EOF_APP_ENV
APP_NAME=ThermaSnap
APP_ENV=production
APP_KEY=${production_app_key}
APP_DEBUG=false
APP_URL=http://127.0.0.1:${production_nginx_port}
LOG_CHANNEL=stderr
LOG_LEVEL=warning
DB_CONNECTION=pgsql
DB_HOST=postgres
DB_PORT=5432
DB_DATABASE=photobooth_smoke
DB_USERNAME=photobooth_smoke
DB_PASSWORD=${production_app_password}
FILESYSTEM_DISK=public
IMAGE_DRIVER=gd
QUEUE_CONNECTION=database
DB_QUEUE_CONNECTION=pgsql
DB_QUEUE_TABLE=jobs
DB_QUEUE=default
DB_QUEUE_RETRY_AFTER=90
QUEUE_FAILED_DRIVER=database-uuids
CACHE_STORE=database
SESSION_DRIVER=database
SESSION_SECURE_COOKIE=false
SESSION_SAME_SITE=lax
MAYA_BASE_URL=https://pg-sandbox.paymaya.com
MAYA_PUBLIC_KEY=
MAYA_SECRET_KEY=
MAYA_WEBHOOK_SECRET=
PHOTOBOOTH_DEFAULT_PRINTER_DRIVER=local_mock
PHOTOBOOTH_PRINT_BRIDGE_ENDPOINT=
PHOTOBOOTH_PRINT_BRIDGE_TIMEOUT_SECONDS=10
PHOTOBOOTH_PRINT_BRIDGE_AUTH_TOKEN=
EOF_APP_ENV

cat > "$production_postgres_env" <<EOF_POSTGRES_ENV
POSTGRES_DB=postgres
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${production_postgres_password}
APP_DB_NAME=photobooth_smoke
APP_DB_USER=photobooth_smoke
APP_DB_PASSWORD=${production_app_password}
BACKUP_DB_USER=photobooth_backup_smoke
BACKUP_DB_PASSWORD=${production_backup_password}
EOF_POSTGRES_ENV

cat > "$production_compose_env" <<EOF_COMPOSE_ENV
THERMASNAP_APP_IMAGE=thermasnap-app:smoke
THERMASNAP_NGINX_IMAGE=thermasnap-nginx:smoke
APP_UID=10001
APP_GID=10001
APP_ENV_FILE=${production_app_env}
POSTGRES_ENV_FILE=${production_postgres_env}
THERMASNAP_MEDIA_PATH=${production_media}
POSTGRES_HOST_PORT=${production_postgres_port}
NGINX_HOST_PORT=${production_nginx_port}
QUEUE_WORKER_TIMEOUT=60
DOCKER_LOG_MAX_SIZE=10m
DOCKER_LOG_MAX_FILES=5
POSTGRES_CPUS=1.0
POSTGRES_MEMORY_LIMIT=1g
APP_CPUS=0.75
APP_MEMORY_LIMIT=768m
WORKER_CPUS=1.0
WORKER_MEMORY_LIMIT=1g
SCHEDULER_CPUS=0.25
SCHEDULER_MEMORY_LIMIT=256m
NGINX_CPUS=0.25
NGINX_MEMORY_LIMIT=128m
EOF_COMPOSE_ENV

chmod 600 "$production_app_env" "$production_postgres_env" "$production_compose_env"

prod_compose config --quiet
prod_compose pull postgres

docker run \
    --rm \
    --entrypoint sh \
    -v "$production_media:/media" \
    postgres:18.6-bookworm \
    -c 'chown -R 10001:10001 /media && chmod 0777 /media'

[[ "$(stat -c '%u:%g' "$production_media")" == "10001:10001" ]]

prod_compose build app nginx

docker run \
    --rm \
    --entrypoint sh \
    thermasnap-app:smoke \
    -c '
        test -f public/build/manifest.json
        ! command -v node >/dev/null 2>&1
        ! command -v npm >/dev/null 2>&1
        ! command -v composer >/dev/null 2>&1
    '

docker run \
    --rm \
    --entrypoint php \
    thermasnap-app:smoke \
    -m > /tmp/thermasnap-php-modules.txt

for extension in \
    bcmath \
    curl \
    dom \
    gd \
    mbstring \
    pcntl \
    pdo_pgsql \
    pdo_sqlite \
    xml \
    zip
do
    grep -iFx "$extension" /tmp/thermasnap-php-modules.txt >/dev/null
done

rm -f /tmp/thermasnap-php-modules.txt

prod_compose up -d postgres
wait_for_container_health "$(prod_compose ps -q postgres)" postgres 45

prod_compose exec -T postgres \
    psql -U postgres -d postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname = 'photobooth_smoke'" \
    | grep -q '^1$'

prod_compose exec -T postgres \
    psql -U postgres -d postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname = 'photobooth_backup_smoke'" \
    | grep -q '^1$'

prod_compose exec -T postgres \
    psql -U postgres -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname = 'photobooth_smoke'" \
    | grep -q '^1$'

prod_compose run --rm --no-deps app php artisan migrate --force
prod_compose up -d app worker scheduler nginx

wait_for_container_health "$(prod_compose ps -q app)" app 45
wait_for_container_health "$(prod_compose ps -q worker)" worker 45
wait_for_container_health "$(prod_compose ps -q scheduler)" scheduler 45
wait_for_container_health "$(prod_compose ps -q nginx)" nginx 45
wait_for_http "http://127.0.0.1:${production_nginx_port}/up" 45

[[ "$(prod_compose exec -T app id -u | tr -d '\r')" == "10001" ]]
[[ "$(prod_compose exec -T app id -g | tr -d '\r')" == "10001" ]]
[[ "$(prod_compose exec -T worker id -u | tr -d '\r')" == "10001" ]]
[[ "$(prod_compose exec -T scheduler id -u | tr -d '\r')" == "10001" ]]

prod_compose exec -T app php artisan config:show database.default | grep -q pgsql
prod_compose exec -T app php artisan config:show filesystems.default | grep -q public
prod_compose exec -T app php artisan config:show queue.default | grep -q database
prod_compose exec -T app php artisan migrate:status >/dev/null

retry_after="$(
    prod_compose exec -T app php -r '
        require "vendor/autoload.php";
        $app = require "bootstrap/app.php";
        $app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();
        echo (int) config("queue.connections.database.retry_after");
    ' | tr -d '\r\n'
)"

queue_worker_timeout=60

[[ "$retry_after" =~ ^[0-9]+$ ]]
(( retry_after > queue_worker_timeout ))

production_schedule_output="$(prod_compose exec -T app php artisan schedule:list)"
grep -q 'photobooth:expire-sessions' <<<"$production_schedule_output"
grep -q 'media:prune-expired' <<<"$production_schedule_output"

prod_compose exec -T app \
    php artisan tinker --execute='dispatch(function (): void { file_put_contents(storage_path("app/public/docker-production-queue-smoke.txt"), "production-queue-ok"); });'

for _ in {1..30}; do
    if [[ -f "$production_media/docker-production-queue-smoke.txt" ]]; then
        break
    fi

    sleep 1
done

test -f "$production_media/docker-production-queue-smoke.txt"
grep -q 'production-queue-ok' "$production_media/docker-production-queue-smoke.txt"

prod_compose exec -T scheduler php artisan schedule:run --verbose

prod_compose exec -T app sh -c '
    mkdir -p storage/app/public/templates storage/app/public/captures storage/app/public/receipts
    printf "production-persistent-media\n" > storage/app/public/docker-production-smoke.txt
    printf "production-public-template\n" > storage/app/public/templates/docker-production-public.txt
    printf "production-private-capture\n" > storage/app/public/captures/docker-production-private.jpg
    printf "production-private-receipt\n" > storage/app/public/receipts/docker-production-private.png
'

curl --fail --silent "http://127.0.0.1:${production_nginx_port}/storage/docker-production-smoke.txt" | grep -q 'production-persistent-media'
curl --fail --silent "http://127.0.0.1:${production_nginx_port}/storage/templates/docker-production-public.txt" | grep -q 'production-public-template'

[[ "$(curl --silent --output /dev/null --write-out '%{http_code}' "http://127.0.0.1:${production_nginx_port}/storage/captures/docker-production-private.jpg")" == "404" ]]
[[ "$(curl --silent --output /dev/null --write-out '%{http_code}' "http://127.0.0.1:${production_nginx_port}/storage/receipts/docker-production-private.png")" == "404" ]]

for service_name in postgres app worker scheduler nginx; do
    assert_production_runtime_bounds "$service_name"
done

prod_compose exec -T -e PGPASSWORD="$production_backup_password" postgres \
    psql -U photobooth_backup_smoke -d photobooth_smoke -tAc 'SELECT count(*) FROM migrations' >/dev/null

cat > "$production_pgpass" <<EOF_PGPASS
postgres:5432:photobooth_smoke:photobooth_backup_smoke:${production_backup_password}
EOF_PGPASS

chmod 600 "$production_pgpass"

cat > "$production_backup_env" <<'EOF_BACKUP_ENV'
BACKUP_DESTINATION=/backups
MEDIA_SOURCE=/media
DB_HOST=postgres
DB_PORT=5432
DB_DATABASE=photobooth_smoke
DB_USERNAME=photobooth_backup_smoke
PGPASSFILE=/run/photobooth/.pgpass
RETENTION_DAYS=14
EOF_BACKUP_ENV

chmod 600 "$production_backup_env"

production_network="$(
    docker inspect \
        --format '{{range $name, $_ := .NetworkSettings.Networks}}{{$name}}{{end}}' \
        "$(prod_compose ps -q postgres)"
)"

docker run \
    --rm \
    --network "$production_network" \
    --entrypoint bash \
    -e BACKUP_CONFIG=/run/photobooth/backup.env \
    -v "$PWD/deploy/production/backup.sh:/usr/local/bin/photobooth-backup:ro" \
    -v "$production_backup_env:/run/photobooth/backup.env:ro" \
    -v "$production_pgpass:/run/photobooth/.pgpass:ro" \
    -v "$production_backups:/backups" \
    -v "$production_media:/media:ro" \
    postgres:18.6-bookworm \
    /usr/local/bin/photobooth-backup

backup_set="$(find "$production_backups" -mindepth 1 -maxdepth 1 -type d ! -name '.*' -print -quit)"

test -n "$backup_set"
test -f "$backup_set/COMPLETE"

(
    cd "$backup_set"
    sha256sum --check SHA256SUMS >/dev/null
)

prod_compose exec -T postgres \
    psql -U postgres -d postgres -c 'DROP DATABASE IF EXISTS photobooth_restore_smoke' >/dev/null

prod_compose exec -T postgres \
    psql -U postgres -d postgres -c 'CREATE DATABASE photobooth_restore_smoke' >/dev/null

docker run \
    --rm \
    --network "$production_network" \
    -e PGPASSWORD="$production_postgres_password" \
    -v "$backup_set:/backup:ro" \
    postgres:18.6-bookworm \
    pg_restore \
        --host=postgres \
        --username=postgres \
        --dbname=photobooth_restore_smoke \
        --no-owner \
        --no-privileges \
        /backup/database.dump

prod_compose exec -T postgres \
    psql -U postgres -d photobooth_restore_smoke -tAc 'SELECT count(*) FROM migrations' \
    | grep -Eq '^[1-9][0-9]*$'

tar \
    --extract \
    --gzip \
    --file="$backup_set/media.tar.gz" \
    --directory="$restored_media"

test -f "$restored_media/docker-production-smoke.txt"
grep -q 'production-persistent-media' "$restored_media/docker-production-smoke.txt"

prod_compose exec -T postgres \
    psql -U postgres -d postgres -c 'DROP DATABASE photobooth_restore_smoke' >/dev/null

prod_compose up -d --force-recreate app worker scheduler nginx

wait_for_container_health "$(prod_compose ps -q app)" app 45
wait_for_container_health "$(prod_compose ps -q worker)" worker 45
wait_for_container_health "$(prod_compose ps -q scheduler)" scheduler 45
wait_for_container_health "$(prod_compose ps -q nginx)" nginx 45
wait_for_http "http://127.0.0.1:${production_nginx_port}/up" 45

curl --fail --silent \
    "http://127.0.0.1:${production_nginx_port}/storage/docker-production-smoke.txt" \
    | grep -q 'production-persistent-media'

prod_compose exec -T app php artisan migrate:status >/dev/null

echo "ThermaSnap development and production Docker smoke verification passed."
